# Generated by Django 5.1 on 2024-08-25 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LQ_Tasks', '0002_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(1, 'F'), (2, 'E'), (3, 'D'), (4, 'C'), (5, 'B'), (6, 'A'), (7, 'S'), (8, 'SS'), (9, 'SSS'), (10, 'EX')])),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('PROCESSING', 'Processing'), ('ON_HOLD', 'On Hold'), ('DEFERRED', 'Deferred'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='LQ_Tasks.task')),
            ],
        ),
    ]
